version: '3.9'
services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    networks:
      - vv-bot
  botapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VV_HOST: "voicevox"
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    networks:
      - vv-bot

networks:
  vv-bot: